cabal-version:      3.0
name:               kinecko-hs
version:            0.1.0.0
-- synopsis:
-- description:
license:            GPL-3.0-or-later
license-file:       LICENSE
author:             Michal Atlas
maintainer:         michal_atlas+git@posteo.net
-- copyright:
build-type:         Simple
-- extra-source-files:

common warnings
    ghc-options: -Wall -fplugin=Polysemy.Plugin

executable kinecko
    import:           warnings
    main-is:          Main.hs
    other-modules:    Network.API.TheMovieDB.Extras
    -- other-extensions:
    build-depends:    base,
                      containers,
                      themoviedb,
                      text,
                      aeson,
                      directory,
                      http-conduit,
                      bytestring,
                      process,
                      polysemy,
                      polysemy-plugin
    hs-source-dirs:   app
    default-language: GHC2024
