name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Run `nix build`
        run: nix build .#kinecko
      - uses: actions/download-artifact@v4
      - name: Run kinecko
        run: nix run -- movies.txt
      - uses: actions/upload-artifact@v4
        with:
          path: |
            config.json
            store
          overwrite: true
        
